### ISSUE TITLE
parseMMCIF Error reading 1ezc.cif and 2wbc.cif

### ISSUE THREAD

**Issue by SHZ66** [prody/ProDy#1364]
The following error was raised while running the ProDy app on `1ezc.cif` and `2wbc.cif`. However, based on the traceback, it looks like this error is not with the app but the mmCIF reader. 

```
Traceback (most recent call last):
  File "/usr/local/bin/prody", line 8, in <module>
    sys.exit(prody_main())
  File "/usr/local/lib/python3.9/site-packages/prody/apps/prody_apps/__init__.py", line 53, in prody_main
    namespace.func(namespace)
  File "/usr/local/lib/python3.9/site-packages/prody/apps/prody_apps/prody_gnm.py", line 300, in <lambda>
    subparser.set_defaults(func=lambda ns: prody_gnm(ns.__dict__.pop('pdb'),
  File "/usr/local/lib/python3.9/site-packages/prody/apps/prody_apps/prody_gnm.py", line 58, in prody_gnm
    pdb = prody.parseMMCIF(pdb, model=model)
  File "/usr/local/lib/python3.9/site-packages/prody/proteins/ciffile.py", line 110, in parseMMCIF
    result = parseMMCIFStream(cif, chain=chain, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prody/proteins/ciffile.py", line 180, in parseMMCIFStream
    ag = _parseMMCIFLines(ag, lines, model, chain, subset,
  File "/usr/local/lib/python3.9/site-packages/prody/proteins/ciffile.py", line 233, in _parseMMCIFLines
    models.append(line.split()[fields['pdbx_PDB_model_num']])
KeyError: 'pdbx_PDB_model_num'
```

@jamesmkrieger Could you give it a look?

**Comment by jamesmkrieger** [comment]
This is now fixed. Just waiting for checks and then will merge it.
