### ISSUE TITLE
Error when running the VMD plugin

### ISSUE THREAD

**Issue by dim-99** [prody/ProDy#1429]
Hi,

I'm using the NMWIZ plugin in VMD to do a PCA analysis using ProDy.

After asking for the path and giving the path for the executable it gives the following error. However, it does produce an output but I'm not sure whether I'm seeing the right output due to the error. 

Traceback (most recent call last):
  File "/usr/local/bin/prody", line 11, in <module>
    load_entry_point('ProDy==2.0', 'console_scripts', 'prody')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/__init__.py", line 88, in <module>
    from . import proteins
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/proteins/__init__.py", line 155, in <module>
    from . import compare
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/proteins/compare.py", line 16, in <module>
    from prody.sequence import MSA
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/sequence/__init__.py", line 53, in <module>
    from . import msa
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/sequence/msa.py", line 9, in <module>
    from Bio import AlignIO
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
Traceback (most recent call last):
  File "/usr/local/bin/prody", line 11, in <module>
    load_entry_point('ProDy==2.0', 'console_scripts', 'prody')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/__init__.py", line 88, in <module>
    from . import proteins
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/proteins/__init__.py", line 155, in <module>
    from . import compare
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/proteins/compare.py", line 16, in <module>
    from prody.sequence import MSA
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/sequence/__init__.py", line 53, in <module>
    from . import msa
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/prody/sequence/msa.py", line 9, in <module>
    from Bio import AlignIO
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/home/dkodituwakku/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
    while executing
"exec $::NMWiz::prody anm --quiet -s $selstr {*}$args "$pdbfn""
    (procedure "::NMWiz::prodySubmitANMjob" line 42)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 22)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

What could be the issue?

Thank you

**Comment by jamesmkrieger** [comment]
I'm not really sure, but it looks like you're using two different python versions or sets of libraries: /usr/lib/python3.8/ and /home/dkodituwakku/.local/lib/python3.8/

**Comment by dim-99** [comment]
Thank you !

**Comment by jamesmkrieger** [comment]
How did you fix this? We have a few more people with similar problems

**Comment by dim-99** [comment]
Hi James,

I couldn't I used ProDy on python and the ProDy command.

As you said I have different python versions.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jamesmkrieger** [comment]
Yes but why is the issue closed? 

Did you manage to make it work by installing prody in a conda environment?

also, what do you mean you can’t use prody in Python or via the command? Do you get an error about pyparsing? That can be fixed by installing from github instead:

pip install git+https://github.com/prody/ProDy.git

**Comment by dim-99** [comment]
I was able to make it work on python and command but not on VMD. Yes it was installed from GitHub. 

I'm working on my university cluster so I can't really do anything about having multiple versions of python. Since it's a problem from my end I closed the issue. Plus command version of ProDy works well for me and I can load the files to VMD after generating the outputs .

**Comment by jamesmkrieger** [comment]
Ah, I read it the other way round. Sorry. Yes, I found the same when I was testing things so it’s somehow vmd related.

You should have some control of which python is active even if you don’t have control over what’s there. You can modify environment variables for your user or use environment managers such as conda.

**Comment by jamesmkrieger** [comment]
You can also talk to the cluster admin

**Comment by jamesmkrieger** [comment]
Please see https://github.com/prody/ProDy/issues/1432 where using conda indeed fixed it
