### ISSUE TITLE
Problem with NMWiz

### ISSUE THREAD

**Issue by xavgit** [prody/ProDy#1432]
Hi,
I have installed Prody from the sources on Ubuntu 20.04.
I'm following the tutorial of NMWiz with the 2k39.pdb. 
When I press the Submit Job button of the NMWiz ProDy Interface panel it appears an
Application Error window with the following message:

Traceback (most recent call last):
  File "/usr/local/bin/prody", line 11, in <module>
    load_entry_point('ProDy==2.0', 'console_scripts', 'prody')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/__init__.py", line 88, in <module>
    from . import proteins
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/__init__.py", line 155, in <module>
    from . import compare
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/compare.py", line 16, in <module>
    from prody.sequence import MSA
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/sequence/__init__.py", line 53, in <module>
    from . import msa
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/sequence/msa.py", line 9, in <module>
    from Bio import AlignIO
  File "/home/xxxx/.local/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/home/xxxx/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
Traceback (most recent call last):
  File "/usr/local/bin/prody", line 11, in <module>
    load_entry_point('ProDy==2.0', 'console_scripts', 'prody')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/__init__.py", line 88, in <module>
    from . import proteins
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/__init__.py", line 155, in <module>
    from . import compare
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/proteins/compare.py", line 16, in <module>
    from prody.sequence import MSA
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/sequence/__init__.py", line 53, in <module>
    from . import msa
  File "/usr/local/lib/python3.8/dist-packages/ProDy-2.0-py3.8-linux-x86_64.egg/prody/sequence/msa.py", line 9, in <module>
    from Bio import AlignIO
  File "/home/xxxx/.local/lib/python3.8/site-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/home/xxxx/.local/lib/python3.8/site-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s $selstr {*}$args "$pdbfn""
    (procedure "::NMWiz::prodySubmitANMjob" line 42)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 22)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

How I can solve this problem?
Thanks
Saverio

**Comment by jamesmkrieger** [comment]
Hi Saverio,

Thanks for reporting this. I had already come across the same problem recently (https://github.com/prody/NMWiz/issues/4) and am going to work out what the problem could be. It sounds like something to do with recent sqlite3 changes, but I don't know.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Also just realised #1429 is the same

**Comment by jamesmkrieger** [comment]
What vmd version are you using?

**Comment by xavgit** [comment]
Thanks for your interest.
/usr/local/lib/vmd/vmd_LINUXAMD64: /usr/lib/x86_64-linux-gnu/libGL.so.1: no version information available (required by /usr/local/lib/vmd/vmd_LINUXAMD64)
Info) VMD for LINUXAMD64, version 1.9.3 (November 30, 2016)

Saverio

**Comment by jamesmkrieger** [comment]
Thanks. Ok, then I can rule out VMD version as the issue. 

Ubuntu version perhaps could be related but not sure

**Comment by xavgit** [comment]
Hi,
I don't know if it can be useful but in the following link there is a discussion about something alike the occurred problem in this issue.
https://bugs.python.org/issue39410
Thanks

Saverio

**Comment by jamesmkrieger** [comment]
Yes, I saw this, thanks. I’ll have another look and give it more thought soon

**Comment by jamesmkrieger** [comment]
Can you try installing ProDy in a conda environment? It might be that conda can help handle these things?

**Comment by xavgit** [comment]
ok.
I'll try with a refresh of conda ...
Thanks.
Saverio

**Comment by jamesmkrieger** [comment]
You're welcome. It looks like VMD is currently using ProDy from the system python

**Comment by xavgit** [comment]
Hi,
with miniconda I receive the following: 
"WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /home/xxxx/miniconda3"
For me it is not possible to make this change as I use Python in the usual way for my activity.
Maybe I don't know how to use conda and Python on the same system.
I will use the command line without the gui if possible.
Thanks

Saverio

**Comment by jamesmkrieger** [comment]
It should be possible to use PYTHONPATH and conda. I do this with Anaconda so that I can use ProDy in place. It's a warning not an error so it may be that everything is fine. 

Have you tried whether this makes the VMD gui work?

**Comment by xavgit** [comment]
Hi,
I've installed mininconda then in a shell 
 conda create -n conda-env python=3.8
 conda activate conda-env
 (conda-env) : git clone https://github.com/prody/ProDy.git
 (conda-env) : cd ProDy/
 (conda-env) :/ProDy python setup.py build_ext --inplace --force
             some required packages installed 
 (conda-env) :/ProDy python setup.py install 
 ....................................................................
 (conda-env) :/ProDy cd 
 (conda-env) : vmd 1dlo.pdb
/usr/local/lib/vmd/vmd_LINUXAMD64: /usr/lib/x86_64-linux-gnu/libGL.so.1: no version information available (required by /usr/local/lib/vmd/vmd_LINUXAMD64)
Info) VMD for LINUXAMD64, version 1.9.3 (November 30, 2016)
Info) http://www.ks.uiuc.edu/Research/vmd/                         
Info) Email questions and bug reports to vmd@ks.uiuc.edu           
Info) Please include this reference in published work using VMD:   
Info)    Humphrey, W., Dalke, A. and Schulten, K., `VMD - Visual   
Info)    Molecular Dynamics', J. Molec. Graphics 1996, 14.1, 33-38.
Info) -------------------------------------------------------------
Info) Multithreading available, 8 CPUs detected.
Info)   CPU features: SSE2 AVX AVX2 FMA 
Info) Free system memory: 2327MB (39%)
Info) No CUDA accelerator devices available.
Warning) Detected X11 'Composite' extension: if incorrect display occurs
Warning) try disabling this X server option.  Most OpenGL drivers
Warning) disable stereoscopic display when 'Composite' is enabled.
Info) OpenGL renderer: AMD Radeon Vega 10 Graphics (raven, LLVM 13.0.0, DRM 3.35, 5.4.0-74-generic)
Info)   Features: STENCIL MSAA(4) MDE CVA MTX NPOT PP PS GLSL(OVFS) 
Info)   Full GLSL rendering mode is available.
Info)   Textures: 2-D (16384x16384), 3-D (512x512x512), Multitexture (8)
Info) Dynamically loaded 2 plugins in directory:
Info) /usr/local/lib/vmd/plugins/LINUXAMD64/molfile
Info) File loading in progress, please wait.
Info) Using plugin pdb for structure file 1dlo.pdb
Info) Using plugin pdb for coordinates from file 1dlo.pdb
Info) Determining bond structure from distance search ...
Info) Finished with coordinate file 1dlo.pdb.
Info) Analyzing structure ...
Info)    Atoms: 7691
Info)    Bonds: 7901
Info)    Angles: 0  Dihedrals: 0  Impropers: 0  Cross-terms: 0
Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
Info)    Residues: 971
Info)    Waters: 0
Info)    Segments: 1
Info)    Fragments: 3   Protein: 3   Nucleic: 0
vmd > Info) Opened coordinate file /home/xxxx/1dlo_gnm.pdb for writing.
Info) Finished with coordinate file /home/xxxx/1dlo_gnm.pdb.
Info) Executing: /home/xxxx/miniconda3/envs/conda-env/bin/python /home/xxxx/miniconda3/envs/conda-env/bin/prody gnm --quiet -s all -o "/home/xxxx" -p "/home/xxxx/1dlo_gnm" -n 10 -c 10 -g 1 "/home/xxxx/1dlo_gnm.pdb"
Info) NMWiz: Parsing file /home/xxxx/1dlo_gnm.nmd
Warning) NMWiz: segnames does not contain any data.
Info) NMWiz: File contains a 1D model.
Info) NMWiz: All segment names are set as "A".
Info) Using plugin pdb for structure file /tmp/.nmdset0.pdb
Info) Using plugin pdb for coordinates from file /tmp/.nmdset0.pdb
Info) Determining bond structure from distance search ...
Info) Analyzing structure ...
Info)    Atoms: 971
Info)    Bonds: 0
Info)    Angles: 0  Dihedrals: 0  Impropers: 0  Cross-terms: 0
Info)    Bondtypes: 0  Angletypes: 0  Dihedraltypes: 0  Impropertypes: 0
Info)    Residues: 971
Info)    Waters: 0
Info)    Segments: 1
Info)    Fragments: 971   Protein: 0   Nucleic: 0
Info) Finished with coordinate file /tmp/.nmdset0.pdb.

It seems that all works fine ...
Now I must study the complete tutorial.

Thanks

Saverio

![nmwiz](https://user-images.githubusercontent.com/18366593/146787102-2b9318ca-5500-4f8c-ae08-63190d3f3d35.png)

**Comment by jamesmkrieger** [comment]
Wonderful!!

Looks like the problem is with the system python not handling sqlite3 properly
