### ISSUE TITLE
local install KDTree error

### ISSUE THREAD

**Issue by skinnerj** [prody/ProDy#145]
I'm getting an error when I attempt to install ProDy-1.1 locally on a linux machine. The Untar and build worked fine. I then installed using the command 'python setup.py install --user'. Installation proceeded without error, but when I python and import prody I get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "prody/**init**.py", line 257, in <module>
    import kdtree
  File "prody/kdtree/**init**.py", line 22, in <module>
    from kdtree import KDTree
  File "prody/kdtree/kdtree.py", line 29, in <module>
    from _CKDTree import KDTree as CKDTree 
ImportError: No module named _CKDTree

I get this even if I'm running from the ~/ProDy-1.1/prody/kdtree/ directory.

This issue doesn't come up when I install as root on a different machine.
Any help will be appreciated.

**Comment by Nabil2017** [comment]
Dear all, 
i installed numpy and prody on my computer (windows 7) and it seems that everything fine. But when i tried to run prody i get an error:
```
C:\>C:\Python34\Scripts\\..\python C:\Python34\Scripts\\prody
Traceback (most recent call last):
  File "C:\Python34\Scripts\\prody", line 6, in <module>
    apps = imp.load_module('prody.apps', *apps)
  File "C:\Python34\lib\imp.py", line 245, in load_module
    return load_package(name, filename)
  File "C:\Python34\lib\imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Python34\lib\site-packages\prody\apps\__init__.py", line 35, in <modu
le>
    from .evol_apps import evol_main, evol_parser, EVOL_APPS
  File "C:\Python34\lib\site-packages\prody\apps\evol_apps\__init__.py", line 82
, in <module>
    *imp.find_module(cmd, [path_apps]))
  File "C:\Python34\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Python34\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "C:\Python34\lib\site-packages\prody\apps\evol_apps\evol_rankorder.py", l
ine 6, in <module>
    import prody
  File "C:\Python34\lib\site-packages\prody\__init__.py", line 63, in <module>
    from . import kdtree
ImportError: cannot import name 'kdtree'
```
any advice? what kdtree may do in the program?
thank you
