### ISSUE TITLE
matchChains uses segnames instead of chids?

### ISSUE THREAD

**Issue by RMeli** [prody/ProDy#1466]
I had some alignments performed with `matchChains` fail unexpectedly with the following error (which is not very explicit, IMHO):
```text
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    m = prody.matchChains(p1, p2, subset="all", overlap=cutoff, seqid=cutoff, pwalign=True)
  File "prody/proteins/compare.py", line 653, in matchChains
    match1, match2, nmatches = getAlignedMatch(simpch1, simpch2)
  File "prody/proteins/compare.py", line 788, in getAlignedMatch
    this = alignment[0][0]
IndexError: list index out of range
```
I was finally able to track down the problem to missing segment identifiers for some residues (which introduce an additional `segname`, `""`), while the `chids` were correct. The problematic PDB file looks as follows:
```text
ATOM   1109  N   LEU A 370      15.943   9.199   9.598  1.00 12.99         A N
ATOM   1110  CA  LEU A 370      15.305   9.031   8.297  1.00  0.00           C
ATOM   1111  C   LEU A 370      15.300   7.535   7.933  1.00  0.00           C
ATOM   1112  O   LEU A 370      16.195   6.829   8.259  1.00 13.99         A O
ATOM   1113  CB  LEU A 370      16.014   9.891   7.256  1.00  0.00           C
ATOM   1114  CG  LEU A 370      15.900  11.395   7.531  1.00  0.00           C
ATOM   1115  CD1 LEU A 370      16.722  12.180   6.521  1.00  0.00           C
ATOM   1116  CD2 LEU A 370      14.509  11.820   7.409  1.00  0.00           C
```
An easy fix is to assign `chids` to `segnames`:
```python
p2.setSegnames(p2.getChids())
```
This gets rid of the error all together and the alignment matches the one the same file manually fixed.

Given that the [documentation](http://prody.csb.pitt.edu/manual/reference/proteins/compare.html#prody.proteins.compare.matchChains) and the name of the function implies the use of chains, I am wondering why the `segname` has such an influence here. Is this expected? AFAIK the segment identifier in PDB files (columns 73-76) is deprecated and [does not appear in the latest PDB file format specification](https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM). Am I missing something?

**Comment by jamesmkrieger** [comment]
Strange. I think it may be to do with the way ProDy identifies chains using the hierarchical view of the protein. 

If there's no segment identifier at all then everything should be fine. The case you have with occasional ones is definitely an edge case that you're better to fix as you did. We don't want to mess up the way things generally work deep within the code if we can help it. 

This could also be something that impacts other functions too though so we'll keep it in mind for now.

Thanks for reporting it.

**Comment by jamesmkrieger** [comment]
These lines are as follows:
chains1 = list(atoms1.getHierView().iterChains())
chains2 = list(atoms2.getHierView().iterChains())

**Comment by RMeli** [comment]
> If there's no segment identifier at all then everything should be fine. The case you have with occasional ones is definitely an edge case that you're better to fix as you did.

Yes, this is definitely an edge case; when there is no segment identifier everything works as expected and the same goes when the segment identifier is present for all atoms. What happens if there is a mismatch between chains and segment identifiers?

> We don't want to mess up the way things generally work deep within the code if we can help it.

Totally understand. But wanted to report this edge case anyways so it will show up in a search, in case other people encounter the same problem.

---

```python
print(list(p1.getHierarchicalView()))
print(list(p1.getHierarchicalView().iterChains())) # equivalent to line 593 of prody/proteins/compare.py
print(list(p2.getHierarchicalView()))
print(list(p2.getHierarchicalView().iterChains())) # equivalent to line 610 of prody/proteins/compare.py
```
This does not seem to work with `p1` and `p2` being objects returned by `prody.parsePDB`:
```
AttributeError: AtomGroup object has no attribute `getHierarchicalView` and 'getHierarchicalView' is not a valid selection string
```
What are `p1` and `p2` in your case?

---

```python
import prody

p1 = prody.parsePDB("2G2I_PRO.pdb")
p2 = prody.parsePDB("2HZI_PRO.pdb")

# FIX
p2.setSegnames(p2.getChids())

cutoff = 90
m = prody.matchChains(p1, p2, subset="all", overlap=cutoff, seqid=cutoff, pwalign=True)

print(m)
```

**Comment by jamesmkrieger** [comment]
Oh, apologies. It should be getHierView() not getHierarchicalView()

If the chain and segment identifiers mismatch then I guess you get broken chains but I’m not sure.

**Comment by jamesmkrieger** [comment]
p1 and p2 came from you. I also parsed things with parsePDB in my copy of the code.

getHierView() should exist for any Atomic object: AtomGroup, Selection, AtomMap, Chain, etc.

**Comment by RMeli** [comment]
> getHierView() should exist for any Atomic object: AtomGroup, Selection, AtomMap, Chain, etc.

Yes, sorry. I should have double checked the name of the function. I get the following:
```
[<Chain: A from 2G2I_PRO (271 residues, 2203 atoms)>, <Chain: B from 2G2I_PRO (265 residues, 2164 atoms)>, <Chain: C from 2G2I_PRO (8 residues, 48 atoms)>, <Chain: D from 2G2I_PRO (7 residues, 49 atoms)>]
[<Chain: A from 2G2I_PRO (271 residues, 2203 atoms)>, <Chain: B from 2G2I_PRO (265 residues, 2164 atoms)>, <Chain: C from 2G2I_PRO (8 residues, 48 atoms)>, <Chain: D from 2G2I_PRO (7 residues, 49 atoms)>]
[<Chain: A from Segment A from 2HZI_PRO_2G2I_LIG (268 residues, 2165 atoms)>, <Chain: B from Segment B from 2HZI_PRO_2G2I_LIG (264 residues, 2109 atoms)>]
[<Chain: A from Segment A from 2HZI_PRO_2G2I_LIG (268 residues, 2165 atoms)>, <Chain: B from Segment B from 2HZI_PRO_2G2I_LIG (264 residues, 2109 atoms)>]
```

**Comment by RMeli** [comment]
Sorry, the above was including my fix. This is what I get without my fix:
```
[<Chain: A from 2G2I_PRO (271 residues, 2203 atoms)>, <Chain: B from 2G2I_PRO (265 residues, 2164 atoms)>, <Chain: C from 2G2I_PRO (8 residues, 48 atoms)>, <Chain: D from 2G2I_PRO (7 residues, 49 atoms)>]
[<Chain: A from 2G2I_PRO (271 residues, 2203 atoms)>, <Chain: B from 2G2I_PRO (265 residues, 2164 atoms)>, <Chain: C from 2G2I_PRO (8 residues, 48 atoms)>, <Chain: D from 2G2I_PRO (7 residues, 49 atoms)>]
[<Chain: A from Segment A from 2HZI_PRO_2G2I_LIG (268 residues, 2144 atoms)>, <Chain: A from Segment  from 2HZI_PRO_2G2I_LIG (3 residues, 21 atoms)>, <Chain: B from Segment B from 2HZI_PRO_2G2I_LIG (264 residues, 2109 atoms)>]
[<Chain: A from Segment A from 2HZI_PRO_2G2I_LIG (268 residues, 2144 atoms)>, <Chain: A from Segment  from 2HZI_PRO_2G2I_LIG (3 residues, 21 atoms)>, <Chain: B from Segment B from 2HZI_PRO_2G2I_LIG (264 residues, 2109 atoms)>]
```

**Comment by jamesmkrieger** [comment]
Ok, thanks

**Comment by RMeli** [comment]
Comparing the two, I think the issue stems from the fact that in the latter chain A is split into two parts, `Chain: A from Segment A` and `Chain: A from Segment  ""` (coming from the empty fields). Therefore, I think the same problem might arise when there is a mismatch between chains and segments?

Many thanks for your help and for the blazing fast replies!

**Comment by jamesmkrieger** [comment]
Yes. I that’s it. 

You’re welcome
