### ISSUE TITLE
parsePDB fails on 4abz

### ISSUE THREAD

**Issue by francoep** [prody/ProDy#1576]
With ProDy version 2.2.0 parsePDB fails on this particular example

```
struct, header = parsePDB('4abz',header=True)
Traceback (most recent call last):
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 214, in _parsePDB
    return parseMMCIF(pdb+chain, **kwargs)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/ciffile.py", line 117, in parseMMCIF
    result = parseMMCIFStream(cif, chain=chain, **kwargs)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/ciffile.py", line 188, in parseMMCIFStream
    hd = getCIFHeaderDict(lines)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/cifheader.py", line 162, in getCIFHeaderDict
    value = func(lines)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/cifheader.py", line 951, in _getPolymers
    ch = data[fields5["pdbx_pdb_strand_id"]]
KeyError: 'pdbx_pdb_strand_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 218, in _parsePDB
    return parseEMD(pdb+chain, **kwargs)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/emdfile.py", line 85, in parseEMD
    raise IOError('EMD file {0} is not available in the directory {1}'
OSError: EMD file 4abz is not available in the directory /net/pulsar/home/koes/paf46/PDBFIX

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "process_receptors_v2.py", line 310, in <module>
    mobile_prot,mobile_header=parsePDB(mobile_id,header=True)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 124, in parsePDB
    return _parsePDB(pdb[0], **kwargs)
  File "/net/pulsar/home/koes/paf46/.local/lib/python3.8/site-packages/prody/proteins/pdbfile.py", line 220, in _parsePDB
    raise IOError('PDB file for {0} could not be downloaded.'
OSError: PDB file for 4abz could not be downloaded.
```

Notably this parsePDB code snippet works in version 2.0.0

**Comment by jamesmkrieger** [comment]
Thanks for reporting. I’ll see what I can do. Sorry something got broken

**Comment by jamesmkrieger** [comment]
I’ll probably put that label in a try/except block.

You can probably use secondary=False in the meantime

**Comment by jamesmkrieger** [comment]
Ok, this is one of those places where we have a data block rather than a loop because mmCIF files can do things either way. I have a way to support that. I just didn't include it for this entry yet.

**Comment by jamesmkrieger** [comment]
I think I've fixed it but I've now come across another problem with the secondary structure assignment, so this will take a while longer.

In the meantime, you can parse this pdb without header information using `secondary=False` in parsePDB

**Comment by jamesmkrieger** [comment]
I've got it now and will be making the pull request soon

**Comment by jamesmkrieger** [comment]
I will merge this once the checks pass and then you can use it by installing prody from github. I'll probably also make a minor release over the next few days/weeks.
