### ISSUE TITLE
Errors parsing multi-model mmCIF

### ISSUE THREAD

**Issue by yannvm** [prody/ProDy#1582]
When I try to parse other than the first NMR model from multiple mmCIF files, I always get the following error.

```python
>>> parseMMCIF("6yfy", model=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/louvre/vmeersch/.local/lib/python3.8/site-packages/prody/proteins/ciffile.py", line 117, in parseMMCIF
    result = parseMMCIFStream(cif, chain=chain, **kwargs)
  File "/home/louvre/vmeersch/.local/lib/python3.8/site-packages/prody/proteins/ciffile.py", line 190, in parseMMCIFStream
    _parseMMCIFLines(ag, lines, model, chain, subset, altloc)
  File "/home/louvre/vmeersch/.local/lib/python3.8/site-packages/prody/proteins/ciffile.py", line 280, in _parseMMCIFLines
    if str(models[i]) != model and str(models[i+1]) == model:
IndexError: list index out of range
```

I also noticed an incorrect behaviors between parsePDB and parseMMCIF.

Different atom numbers when specifying the model number in parseMMCIF.
```python
>>> parsePDB("6yfy", chain="A")
@> PDB file is found in working directory (6yfy.pdb.gz).
@> 187 atoms and 26 coordinate set(s) were parsed in 0.11s.
<AtomGroup: 6yfyA (187 atoms; active #0 of 26 coordsets)>
>>> 
>>> parsePDB("6yfy", chain="A", model=1)
@> PDB file is found in working directory (6yfy.pdb.gz).
@> 187 atoms and 1 coordinate set(s) were parsed in 0.07s.
<AtomGroup: 6yfyA (187 atoms)>
```
and  
```python
>>> parseMMCIF("6yfy", chain="A")
@> WARNING Could not find _atom_site_anisotrop in lines.
@> WARNING No anisotropic B factors found
@> 187 atoms and 26 coordinate set(s) were parsed in 0.35s.
<AtomGroup: 6yfy_A (187 atoms; active #0 of 26 coordsets)>
>>> 
>>> parseMMCIF("6yfy", chain="A", model=1)
@> WARNING Could not find _atom_site_anisotrop in lines.
@> WARNING No anisotropic B factors found
@> 1460 atoms and 1 coordinate set(s) were parsed in 0.20s.
<AtomGroup: 6yfy_A (1460 atoms)>
```

#### Edit: An issue I experienced was corrected in ProDy 2.2.0. I updated the comment accordingly.

**Comment by jamesmkrieger** [comment]
Thanks for reporting. I’ll try and figure it out late next week when I’m back from a conference trip.

**Comment by jamesmkrieger** [comment]
ok, update noted

**Comment by jamesmkrieger** [comment]
I have fixes now for all these cases in the linked pull request

**Comment by jamesmkrieger** [comment]
I'll add tests to it and then merge it if everything passes again

**Comment by jamesmkrieger** [comment]
This is now merged and you should be able to access it if you update prody from github
