### ISSUE TITLE
error save figure pca

### ISSUE THREAD

**Issue by aspitaleri** [prody/ProDy#1644]
Hi 
I am using prody to generate pca data. I am using your input to test the installation (http://prody.csb.pitt.edu/tutorials/trajectory_analysis/trajectory_analysis_files.tgz). The problem is with the option -R (--cross-correlations-figure). Here it is my test to help you to understand:

`prody pca -a -J "1,2" -F svg/png/pdf -p test --select calpha --pdb mdm2.pdb mdm2.dcd `

It works fine (3 options)

`prody pca -a -J "1,2" -Q -F svg/png/pdf -p test --select calpha --pdb mdm2.pdb mdm2.dcd `

it works fine (3 options)

`prody pca -a -R -F svg/png/pdf -p test --select calpha --pdb mdm2.pdb mdm2.dcd `
and
`prody pca -a -J "1,2" -Q -R -F svg/png/pdf -p test --select calpha --pdb mdm2.pdb mdm2.dcd`

produces the following error:

@> Writing numerical output.
@> Saving graphical output.
Traceback (most recent call last):
  File "/group/davila/ENVS/MDpy3.9/bin/prody", line 8, in <module>
    sys.exit(prody_main())
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/prody/apps/prody_apps/__init__.py", line 57, in prody_main
    namespace.func(namespace)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/prody/apps/prody_apps/prody_pca.py", line 336, in <lambda>
    subparser.set_defaults(func=lambda ns: prody_pca(ns.dcd, **ns.__dict__))
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/prody/apps/prody_apps/prody_pca.py", line 226, in prody_pca
    plt.savefig(join(outdir, prefix + '_cc.'+format),
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/pyplot.py", line 959, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/figure.py", line 3285, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/_api/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/backends/backend_svg.py", line 1400, in print_svg
    self.figure.draw(renderer)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/figure.py", line 3082, in draw
    mimage._draw_list_compositing_images(
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/axes/_base.py", line 3100, in draw
    mimage._draw_list_compositing_images(
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/image.py", line 156, in _draw_list_compositing_images
    a.draw(renderer)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/lines.py", line 799, in draw
    gc.set_dashes(*self._dash_pattern)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/matplotlib-3.6.3-py3.9-linux-x86_64.egg/matplotlib/backend_bases.py", line 926, in set_dashes
    raise ValueError(
ValueError: At least one value in the dash list must be positive

Actually it generates test_cc.pdf but it is corrupted (0K), test_cc.svg is generated (with the aforementioned error too) and test_cc.png is not generated at all.

I have installed prody in its own env using pip, python3.9 and matplotlib 3.6.9. 

Thanks for help

Best

**Comment by aspitaleri** [comment]
I tried Prody-2.3.0 too but got similar error

**Comment by jamesmkrieger** [comment]
PCA on homogeneous ensembles shouldn't have changed in a long time, so this is unlikely to be a versions problem

It's the installation things that could be

Please stop commenting for now and give me time to test it another day

**Comment by aspitaleri** [comment]
Sure - just to tell you that I have done a clean installation on a new vanilla python environment but still identical error with Prody-2.3.0 (the previous test was don on prody from a share python environment)

**Comment by jamesmkrieger** [comment]
I think the issue here is that the latest matplotlib is more sensitive and doesn't like the interactive mode on showMatrix, which is True by default. Setting it to False in the pca app fixes the problem and I'll make the same fix to all the others. 

Thanks for reporting this
