### ISSUE TITLE
Failing to import prody on multiple version due to missing(?) `path_item` in `pkgutil.get_importer` ..

### ISSUE THREAD

**Issue by rtviii** [prody/ProDy#1721]
This keeps happening to me for some reason since i moved to MacOS ( although im not claiming that's the reason):
1. I create a fresh python environment and install prody along with some other packages into it.
2. I attempt to run some scripts that import prody functions..
3. I get the following error related to `frozen <zipimport>` or `pkgutil` that i'm not sure how to diagnose. I generally deduce that it probably is related to name resolutions and symlinks since similar errors popped up for me previosuly in imporperly managed python3 environments. So i tried a bunch of different things: python3.8, 3.10, 3.11 along with `poetry`, `pyenv virtualenv` and vanilla `virtualenv` (below are two examples from `pyenv`), but seem to get the same thing every time. 

Can someone point me where to take a look further? 

The crucial clue is that in the sister folder of the project that fails (as below) sits a smaller project that works just fine with importing the exact same stuff from prody and having the same dependencies. I have no clue what is different between the two.

# `pyenv virtualenv` with python3.10:

```bash
Traceback (most recent call last):
  File "/Users/rtviii/.pyenv/versions/3.10.12/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rtviii/dev/riboxyz/api/cli.py", line 8, in <module>
    from ribctl.etl.ribosome_assets import Assetlist, RibosomeAssets, obtain_assets, obtain_assets_processpool, obtain_assets_threadpool
  File "/Users/rtviii/dev/riboxyz/api/ribctl/etl/ribosome_assets.py", line 9, in <module>
    from ribctl.lib.msalib import AMINO_ACIDS_1_TO_3_CODE, AMINO_ACIDS_3_TO_1_CODE
  File "/Users/rtviii/dev/riboxyz/api/ribctl/lib/msalib.py", line 16, in <module>
    from prody import MSA, MSAFile, parseMSA
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/__init__.py", line 81, in <module>
    from . import atomic
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/atomic/__init__.py", line 148, in <module>
    from .atom import *
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/atomic/atom.py", line 9, in <module>
    from .pointer import AtomPointer
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/atomic/pointer.py", line 7, in <module>
    from .atomic import Atomic
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/atomic/atomic.py", line 19, in <module>
    with openData('mod_res_map.dat') as f:
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/utilities/misctools.py", line 428, in openData
    return open(getDataPath(filename), mode)
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/prody/utilities/misctools.py", line 424, in getDataPath
    import pkg_resources
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    ws = cls()
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/rtviii/.pyenv/versions/ribxz_3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1988, in find_distributions
    importer = get_importer(path_item)
  File "/Users/rtviii/.pyenv/versions/3.10.12/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen zipimport>", line 67, in __init__
  File "/Users/rtviii/.pyenv/versions/3.10.12/lib/python3.10/os.py", line 823, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

# `pyenv virtualenv` with python3.11 :

```bash
(ribxz_pyvenv) ᢹ saeta.rtviii[ dev/riboxyz ]  p3 api/cli.py                                                                                                    [master] 
Traceback (most recent call last):
  File "/Users/rtviii/dev/riboxyz/api/cli.py", line 8, in <module>
    from ribctl.etl.ribosome_assets import Assetlist, RibosomeAssets, obtain_assets, obtain_assets_processpool, obtain_assets_threadpool
  File "/Users/rtviii/dev/riboxyz/api/ribctl/etl/ribosome_assets.py", line 9, in <module>
    from ribctl.lib.msalib import AMINO_ACIDS_1_TO_3_CODE, AMINO_ACIDS_3_TO_1_CODE
  File "/Users/rtviii/dev/riboxyz/api/ribctl/lib/msalib.py", line 16, in <module>
    from prody import MSA, MSAFile, parseMSA
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/__init__.py", line 81, in <module>
    from . import atomic
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/atomic/__init__.py", line 148, in <module>
    from .atom import *
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/atomic/atom.py", line 9, in <module>
    from .pointer import AtomPointer
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/atomic/pointer.py", line 7, in <module>
    from .atomic import Atomic
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/atomic/atomic.py", line 19, in <module>
    with openData('mod_res_map.dat') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/utilities/misctools.py", line 428, in openData
    return open(getDataPath(filename), mode)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/prody/utilities/misctools.py", line 424, in getDataPath
    import pkg_resources
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
         ^^^^^
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rtviii/.pyenv/versions/ribxz_pyvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2075, in find_distributions
    importer = get_importer(path_item)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pkgutil.py", line 416, in get_importer
    path_item = os.fsdecode(path_item)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 824, in fsdecode
  ```
  
 `requirements.txt`:
 ```text
 annotated-types==0.5.0
attrs==23.1.0
biopython==1.79
certifi==2023.5.7
charset-normalizer==3.1.0
ete3==3.1.3
fuzzysearch==0.7.3
fuzzywuzzy==0.18.0
gemmi==0.6.2
idna==3.4
Levenshtein==0.20.9
loguru==0.7.0
numpy==1.23.5
ProDy==2.4.0
pydantic==1.10.5
pydantic_core==2.0.1
pyparsing==3.1.0
rapidfuzz==2.15.1
requests==2.31.0
scipy==1.11.1
six==1.16.0
typing_extensions==4.7.1
urllib3==2.0.3
```
 ```

**Comment by jamesmkrieger** [comment]
Have you tried conda? We usually recommend using that. I don’t see why the others would have problems but we haven’t tested them, so they might

**Comment by jamesmkrieger** [comment]
What's your setuptools version? It has had some changes recently that have broken some other packages, so I guess it could be worth downgrading to setuptools==66.0.0 and seeing if it's the case here.

Also, are you able to import other packages like numpy and scipy in these environments? Does it make a difference which directory you try from, e.g. have you tried in your home directory?

**Comment by jamesmkrieger** [comment]
I’d also suggest not using python 3.11 but not sure what’s wrong for python 3.10

**Comment by rtviii** [comment]
@jamesmkrieger , tried with 3.8 as well, same `fstring` error somewhere deep inside the package. Had to move to back to Biopython unfortunately.

**Comment by jamesmkrieger** [comment]
Ok, I’ll see if I can fix it

**Comment by jamesmkrieger** [comment]
This is a problem with pkg_resources, which is distributed with setuptools, and not with ProDy itself. Did you try downgrading setuptools?

I have setuptools 61.2.0 and this works fine.

**Comment by jamesmkrieger** [comment]
I actually don't even have this problem with setuptools 68.2.0, but maybe it's something to do with your system setup. I did see something that said there are more problems with pkg_resources in virtual envs

Anyhow I've made a branch https://github.com/jamesmkrieger/ProDy/tree/importlib_resources with a possible fix for this by using importlib.resources if the pkg_resources block fails

**Comment by jamesmkrieger** [comment]
I am now trying to reproduce your problem with venv and see what happens.

**Comment by jamesmkrieger** [comment]
I've tried this with python 3.10.13 and 3.8.13, changing requirements.txt to scipy==1.10.1 for python 3.8.13

Both work with no problem

**Comment by rtviii** [comment]
That might be (re MacOS), but i found the same (word for word) issue on nix(Arch) later this fall as well (`setuptools==65.5.0`). 

Granted, it was the same big project with labyrinthine imports.  As far as i remember i managed to get around it once or twice by changing the module structure and isolating all the code that uses the MSA modules (that's the only part of ProDy that i used), but that is obviously a hack and i couldn't reporoduce this at a gunpoint now. I'm sure though that it wasn't any of my modules masking the imported ones or any of these regular python import system soup things.

Thanks for digging deep on this. I feel bad if i rang a false alarm here, i'll try to report more thoroughly next time i use ProDy if i encounter this.

**Comment by jamesmkrieger** [comment]
No worries.

If you found it on a non MacOS system, then maybe there is something going on more generally. Can you try again to reproduce the problem on that system please? I don't think you need to reproduce the hack to fix it!

That said, I guess it could be nice to be able to import certain parts of prody (e.g. the MSA tools) without depending on other parts that may not work.

Best wishes
James

**Comment by rtviii** [comment]
Just installed `ProDy==2.4.1` to the same project, imported, ran:
```python3
from prody import MSAFile, MSA, parseMSA
msa  = MSAFile(os.path.join(ASSETS['fasta_rna'], 'tRNA.fasta'))
```
Works now. It's a mystery to me.

**Comment by jamesmkrieger** [comment]
I'm glad to hear it's working

Let's close the issue and you can reopen it if needed

It could be there was a temporary bug with setuptools and pkg_resources that is now fixed or something like that

**Comment by rtviii** [comment]
Thanks again, James.

**Comment by jamesmkrieger** [comment]
You're welcome
