### ISSUE TITLE
A weird bug of prody 2.4.1 on Python 3.9.0

### ISSUE THREAD

**Issue by JinyinZha** [prody/ProDy#1856]
In brief, there seems to require a warm up before making selections.

> Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import prody
>>> p = prody.parsePDB("/home/jyzha/project/sample/data/conf_diff/neb/P02699_1to348/1F88_A_fixed.pdb").select("resnum 1 to 309")
@> 2746 atoms and 1 coordinate set(s) were parsed in 0.04s.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/prody/atomic/atomic.py", line 232, in select
    return SELECT.select(self, selstr, **kwargs)
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/prody/atomic/select.py", line 895, in select
    indices = self.getIndices(atoms, selstr, **kwargs)
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/prody/atomic/select.py", line 953, in getIndices
    torf = self.getBoolArray(atoms, selstr, **kwargs)
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/prody/atomic/select.py", line 1004, in getBoolArray
    parser = self._getParser(selstr)
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/prody/atomic/select.py", line 1103, in _getParser
    parser.enablePackrat()
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
  File "/home/jyzha/software/anaconda3/envs/openmm/lib/python3.9/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
TypeError: can't multiply sequence by non-int of type 'Forward'
>>> p = prody.parsePDB("/home/jyzha/project/sample/data/conf_diff/neb/P02699_1to348/1F88_A_fixed.pdb").select("resnum 1 to 309")
@> 2746 atoms and 1 coordinate set(s) were parsed in 0.04s.
>>> prody.__version__
'2.4.1'
>>>

**Comment by jamesmkrieger** [comment]
Please downgrade your pyparsing to 3.1.1

This is a known error already
