### ISSUE TITLE
ImportError: druggability package was not found

### ISSUE THREAD

**Issue by accibio** [prody/ProDy#1917]
Hi,
I am trying to run the **_Calculate Grids_** module of DruGUI in VMD. After loading the PSF, PDB and DCD files, when I run it, few **_.dx_** and **_.dcd_** files are generated but an **_Application Error_** popup window appears midway while writing the **prot_positive.dx_** file along with this message:

> Traceback (most recent call last):
  File "/home/DruGUI/Calculate_Grids/prot.py", line 21, in <module>
    'to proceed with calculation'.format(__file__))
ImportError: druggability package was not found. Edit /home/DruGUI/Calculate_Grids/prot.py to proceed with calculation
Traceback (most recent call last):
  File "/home/DruGUI/Calculate_Grids/prot.py", line 21, in <module>
    'to proceed with calculation'.format(__file__))
ImportError: druggability package was not found. Edit /home/DruGUI/Calculate_Grids/prot.py to proceed with calculation
    while executing
"exec $pythonexe [file join "$outputdir" "$pyprefix.py"] critical"
    (procedure "::druggability::Assess_druggability" line 20)
    invoked from within
"::druggability::Assess_druggability"
    (procedure "::druggability::Process_system" line 218)
    invoked from within
"::druggability::Process_system"
    invoked from within
".druggui.main_frame.process.button invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .druggui.main_frame.process.button"
    (command bound to event)
 
I am using Python2.7. Similar issue was posted here #180 but the solution is not clear to me. Please help. 
Thanks!

**Comment by AnthonyBogetti** [comment]
Hi @accibio, I apologize that your issue was not responded to. Are you still having this issue? Please let me know.
