### ISSUE TITLE
Tk Figure Successive Calls Error

### ISSUE THREAD

**Issue by melrom** [prody/ProDy#198]
If you call `showProtein()` and leave the Tk window open, then call `showOverlapTable()`, you will get the following error:

```python
In [152]: showOverlapTable(pca[:4], anm[:4]);

In [153]: Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1473, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 534, in callit
    func(*args)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 363, in idle_draw
    self.draw()
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 348, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 440, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1006, in draw
    func(*args)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 248, in draw
    for col in self.collections]
AttributeError: 'PolyCollection' object has no attribute 'do_3d_projection'
```

I presume it is having trouble overwriting the existing window. This does not occur if you were to do it in the opposite order (e.g., `showOverlapTable()` then `showProtein()`) or if there is no existing window open.

**Comment by cihankayacihan** [comment]
We tend to leave this to user because some users because this is obviously an issue related to matplotlib.
