### ISSUE TITLE
s390 architectures

### ISSUE THREAD

**Issue by sagitter** [prody/ProDy#266]
Does ProDy support s390 architectures ?
Some tests are failed on them:

```
======================================================================
ERROR: Failure: IOError (Unrecognized DCD header or unsupported DCD format.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/ensemble/__init__.py", line 13, in <module>
    DCD = parseDatafile('dcd')
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/datafiles/__init__.py", line 151, in parseDatafile
    return PARSERS[splitext(fn)[1]](fn, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 494, in parseDCD
    dcd = DCDFile(filename, astype=astype)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: testMSF (prody.tests.measure.test_measure.TestMSF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/measure/test_measure.py", line 106, in testMSF
    dcd = DCDFile(pathDatafile('dcd'))
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: testMSFfloat (prody.tests.measure.test_measure.TestMSF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/measure/test_measure.py", line 113, in testMSFfloat
    dcd = DCDFile(pathDatafile('dcd'), astype=float)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: Failure: IOError (Unrecognized DCD header or unsupported DCD format.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/trajectory/test_dcdfile.py", line 11, in <module>
    from prody.tests.ensemble import ALLATOMS, ENSEMBLE, RTOL, ATOL, DCD
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/ensemble/__init__.py", line 13, in <module>
    DCD = parseDatafile('dcd')
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/datafiles/__init__.py", line 151, in parseDatafile
    return PARSERS[splitext(fn)[1]](fn, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 494, in parseDCD
    dcd = DCDFile(filename, astype=astype)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: Failure: IOError (Unrecognized DCD header or unsupported DCD format.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/trajectory/test_frame.py", line 12, in <module>
    DCD = Trajectory(pathDatafile('dcd'))
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/trajectory.py", line 33, in __init__
    self.addFile(name)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/trajectory.py", line 104, in addFile
    traj = openTrajFile(filename, **(kwargs or self._kwargs))
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/__init__.py", line 44, in openTrajFile
    return TRAJFILE[ext](filename, *args, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
FAIL: testMATLAB (prody.tests.sequence.test_analysis.TestCalcSCA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/sequence/test_analysis.py", line 536, in testMATLAB
    assert_array_almost_equal(expect, result, err_msg='turbo failed')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
turbo failed
(mismatch 81.0%)
 x: array([[ -3.425844e+241,   2.556503e-111,  -1.749712e+003,   0.000000e+000,
         -1.681252e-191,  -4.008701e-114,   2.875855e-074,   9.566247e-093,
         -1.292457e-249,  -3.925164e-168],...
 y: array([[ 0.321199,  0.072137,  0.030741,  0.      ,  0.050852,  0.16432 ,
         0.041369,  0.289206,  0.087419,  0.035697],
       [ 0.072137,  0.816631,  0.035063,  0.      ,  0.012006,  0.364268,...
-------------------- >> begin captured logging << --------------------
.prody: DEBUG: SCA matrix was calculated in 0.00s.
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: testMATLAB10 (prody.tests.sequence.test_analysis.TestDirectInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/sequence/test_analysis.py", line 1198, in testMATLAB10
    assert_array_almost_equal(expect, result, err_msg='refine failed')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
refine failed
(mismatch 87.5%)
 x: array([[  0.000000e+000,   1.625806e-028,   3.555451e-017,  -1.228789e+180,
          1.893848e+193,   1.648498e-108,   3.815168e-295,   9.649142e-109],
       [  1.625806e-028,   0.000000e+000,   2.672622e+059,  -1.100353e-256,...
 y: array([[ 0.      ,  1.030514,  1.034746,  0.26286 ,  0.778531,  0.559159,
         0.646177,  0.567633],
       [ 1.030514,  0.      ,  1.161546,  0.148573,  0.728448,  0.528643,...
-------------------- >> begin captured logging << --------------------
.prody: DEBUG: DI matrix was calculated in 0.01s.
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: testMATLAB8 (prody.tests.sequence.test_analysis.TestDirectInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.7.1-2.fc23.s390x/usr/lib64/python2.7/site-packages/prody/tests/sequence/test_analysis.py", line 1188, in testMATLAB8
    expect, result, err_msg='w/out refine failed')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
w/out refine failed
(mismatch 87.5%)
 x: array([[  0.000000e+000,   1.625806e-028,   3.555451e-017,  -1.228789e+180,
          1.893848e+193,   1.648498e-108,   3.815168e-295,   9.649142e-109],
       [  1.625806e-028,   0.000000e+000,   2.672622e+059,  -1.100353e-256,...
 y: array([[ 0.      ,  1.030514,  1.034746,  0.26286 ,  0.778531,  0.559159,
         0.646177,  0.567633],
       [ 1.030514,  0.      ,  1.161546,  0.148573,  0.728448,  0.528643,...
-------------------- >> begin captured logging << --------------------
.prody: DEBUG: DI matrix was calculated in 0.01s.
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
```

Full log: http://s390.koji.fedoraproject.org/kojifiles/work/tasks/738/1990738/build.log

**Comment by cihankayacihan** [comment]
It is not supporting s390 structures. But I am adding this as a feature request.

**Comment by jamesmkrieger** [comment]
Please could you try with the latest ProDy (1.10.7) and tell us if you still have this problem. Thanks
