### ISSUE TITLE
[ProDy-1.8] testHessian/testProjection failed

### ISSUE THREAD

**Issue by sagitter** [prody/ProDy#300]
Hi all,

`testHessian` and `testProjection` tests are failed during ProDy building on Fedora 25 (development branch):
```

======================================================================
FAIL: testHessian (prody.tests.dynamics.test_enms.TestRTB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.1-1.fc25.i386/usr/lib/python2.7/site-packages/prody/tests/dynamics/test_enms.py", line 296, in testHessian
    err_msg='expected Hessian is not produced')
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0, atol=1e-05
expected Hessian is not produced
(mismatch 100.0%)
 x: array([[  8.720727e+00,   1.168919e+00,  -1.192337e+00,  -1.340542e+00,
          3.799043e-01,  -6.114914e-03,  -1.195256e-01,  -2.708178e-01,
         -3.089641e-02,  -3.278016e-01,   2.910643e-02,  -8.714530e-02,...
 y: array([[ 4.180874,  0.480677, -0.884969, -0.676511,  0.200856,  0.099307,
         0.0809  ,  0.156824, -0.215859, -0.976119, -0.413184,  0.254024,
         0.141282, -0.389296, -0.248138,  0.480677,  1.796648, -1.002386,...
======================================================================
FAIL: testProjection (prody.tests.dynamics.test_enms.TestRTB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.1-1.fc25.i386/usr/lib/python2.7/site-packages/prody/tests/dynamics/test_enms.py", line 302, in testProjection
    err_msg='expected projection matrix is not produced')
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0, atol=1e-05
expected projection matrix is not produced
(mismatch 20.4144620811%)
 x: array([[  1.000000e+00,   0.000000e+00,   0.000000e+00, ...,
          0.000000e+00,   0.000000e+00,   0.000000e+00],
       [  0.000000e+00,   1.000000e+00,   0.000000e+00, ...,...
 y: array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],...
----------------------------------------------------------------------
Ran 285 tests in 2.827s
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/5982/14065982/build.log

**Comment by cihankayacihan** [comment]
hi. we cannot reproduce the error in fedora 23. We suggest you to use ProDy on a stable OS. We will test it on fc25 but we cannot guarantee that we can resolve this issue.
