### ISSUE TITLE
Unrecognized DCD header or unsupported DCD format (PowerPC)

### ISSUE THREAD

**Issue by sagitter** [prody/ProDy#347]
Hi all.

Three tests are failed on PowerPC-64 architecture:

```
+ PYTHONPATH=/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages
+ nosetests --verbosity=2 -e test_select.py -e test_enms.py -w /builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests --tests prody -a '!slow'
/usr/lib64/python2.7/site-packages/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
testAtomGroup (prody.tests.atomic.test_atomic.TestAtomIterations) ... ok
testAtomMap (prody.tests.atomic.test_atomic.TestAtomIterations) ... ok
testChain (prody.tests.atomic.test_atomic.TestAtomIterations) ... ok
testResidue (prody.tests.atomic.test_atomic.TestAtomIterations) ... ok
testSelection (prody.tests.atomic.test_atomic.TestAtomIterations) ... ok
TestCopyAtom (prody.tests.atomic.test_atomic.TestCopying) ... ok
TestCopyAtomGroup (prody.tests.atomic.test_atomic.TestCopying) ... ok
TestCopyChain (prody.tests.atomic.test_atomic.TestCopying) ... ok
TestCopySelstr (prody.tests.atomic.test_atomic.TestCopying) ... ok
testAtom (prody.tests.atomic.test_atomic.TestPickling) ... ok
testAtomGroup (prody.tests.atomic.test_atomic.TestPickling) ... ok
testSelection (prody.tests.atomic.test_atomic.TestPickling) ... ok
testSaveLoad (prody.tests.atomic.test_atomic.TestSaveLoad) ... ok
testInstantiation (prody.tests.atomic.test_atommap.TestInstantiation) ... ok
testAllSelection (prody.tests.atomic.test_atommap.TestSelection) ... ok
testChainSelection (prody.tests.atomic.test_atommap.TestSelection) ... ok
testGetBoolArray (prody.tests.atomic.test_atommap.TestSelection) ... ok
testNameSelection (prody.tests.atomic.test_atommap.TestSelection) ... ok
testSplit (prody.tests.atomic.test_fragment.TestFragment) ... ok
testSplitCopy (prody.tests.atomic.test_fragment.TestFragment) ... ok
testSplitNoh (prody.tests.atomic.test_fragment.TestFragment) ... ok
testSplitNohCopy (prody.tests.atomic.test_fragment.TestFragment) ... ok
testWhole (prody.tests.atomic.test_fragment.TestFragment) ... ok
testWhole2 (prody.tests.atomic.test_fragment.TestFragment) ... ok
testWholeAll (prody.tests.atomic.test_fragment.TestFragment) ... ok
testWholeCopy (prody.tests.atomic.test_fragment.TestFragment) ... ok
testWholeNoh (prody.tests.atomic.test_fragment.TestFragment) ... ok
testWholeNohCopy (prody.tests.atomic.test_fragment.TestFragment) ... ok
testCA (prody.tests.atomic.test_hierview.TestShuffled) ... ok
testProtein (prody.tests.atomic.test_hierview.TestShuffled) ... ok
testNumResidues (prody.tests.atomic.test_hierview.TestTerRecord) ... ok
testResidueIndexing (prody.tests.atomic.test_hierview.TestTerRecord) ... ok
testSelectionResidueIndexing (prody.tests.atomic.test_hierview.TestTerRecord) ... ok
testSelectionResidueIndexing2 (prody.tests.atomic.test_hierview.TestTerRecord) ... ok
testSetData (prody.tests.atomic.test_subset.TestUserData) ... ok
testMode1d (prody.tests.dynamics.test_editing.TestExtending) ... ok
testMode3d (prody.tests.dynamics.test_editing.TestExtending) ... ok
testModel1d (prody.tests.dynamics.test_editing.TestExtending) ... ok
testModel3d (prody.tests.dynamics.test_editing.TestExtending) ... ok
testVector1d (prody.tests.dynamics.test_editing.TestExtending) ... ok
testVector3d (prody.tests.dynamics.test_editing.TestExtending) ... ok
Failure: IOError (Unrecognized DCD header or unsupported DCD format.) ... ERROR
testAllSearch (prody.tests.kdtree.test_kdtree.TestKDTree) ... ok
testSearch (prody.tests.kdtree.test_kdtree.TestKDTree) ... ok
testPairNoPBC (prody.tests.kdtree.test_kdtree.TestKDTreePBC) ... ok
testPairPBC (prody.tests.kdtree.test_kdtree.TestKDTreePBC) ... ok
testPointNoPBC (prody.tests.kdtree.test_kdtree.TestKDTreePBC) ... ok
testPointPBC (prody.tests.kdtree.test_kdtree.TestKDTreePBC) ... ok
testMINvsMAX (prody.tests.measure.test_contacts.TestContacts) ... ok
testPBCvsNONE (prody.tests.measure.test_contacts.TestContacts) ... ok
testAtomicArgumentSwitching (prody.tests.measure.test_contacts.TestNeighbors) ... ok
testCoordArgumentSwitching (prody.tests.measure.test_contacts.TestNeighbors) ... ok
testNoPBC (prody.tests.measure.test_contacts.TestNeighbors) ... ok
testPBC (prody.tests.measure.test_contacts.TestNeighbors) ... ok
testPBCAtomicArgumentSwitching (prody.tests.measure.test_contacts.TestNeighbors) ... ok
testPBCCoordArgumentSwitching (prody.tests.measure.test_contacts.TestNeighbors) ... ok
testCenter (prody.tests.measure.test_measure.TestCenter) ... ok
testCenterWithWeights (prody.tests.measure.test_measure.TestCenter) ... ok
testMultiCoordsets (prody.tests.measure.test_measure.TestCenter) ... ok
testMultiCoordsetsWithWeights (prody.tests.measure.test_measure.TestCenter) ... ok
testCTerPhi (prody.tests.measure.test_measure.TestDihedrals) ... ok
testCTerPsi (prody.tests.measure.test_measure.TestDihedrals) ... ok
testCalcPhi (prody.tests.measure.test_measure.TestDihedrals) ... ok
testCalcPsi (prody.tests.measure.test_measure.TestDihedrals) ... ok
testNTerPhi (prody.tests.measure.test_measure.TestDihedrals) ... ok
testNTerPsi (prody.tests.measure.test_measure.TestDihedrals) ... ok
testPBC (prody.tests.measure.test_measure.TestDistances) ... ok
testPBCSymmetry (prody.tests.measure.test_measure.TestDistances) ... ok
testMSF (prody.tests.measure.test_measure.TestMSF) ... ERROR
testMSFfloat (prody.tests.measure.test_measure.TestMSF) ... ERROR
testByArgument (prody.tests.measure.test_transform.TestMoveAtoms) ... ok
testToArgument (prody.tests.measure.test_transform.TestMoveAtoms) ... ok
testTransformation (prody.tests.measure.test_transform.TestMoveAtoms) ... ok
testWrap (prody.tests.measure.test_transform.TestWrapAtoms) ... ok
testHeaderContent (prody.tests.proteins.test_header.TestParsePDBHeaderOnly) ... ok
testHeaderType (prody.tests.proteins.test_header.TestParsePDBHeaderOnly) ... ok
Test outcome of passing invalid PDB identifiers. ... ok
Test number of coordinate sets when using *ag* arguments. ... ok
Test number of coordinate sets when using *ag* arguments. ... ok
Test outcome of valid and invalid *ag* arguments. ... ok
testBiomolArgument (prody.tests.proteins.test_pdbfile.TestParsePDB) ... ok
Test outcome of valid and invalid *chain* arguments. ... ok
Test outcome of valid and invalid *model* arguments. ... ok
Test outcome of invalid *pdb* arguments. ... ok
testSecondaryArgument (prody.tests.proteins.test_pdbfile.TestParsePDB) ... ok
Test outcome of valid and invalid *subset* arguments. ... ok
Test outcome of *title* argument. ... ok
Test the outcome of a simple parsing scenario. ... ok
testAltlocA (prody.tests.proteins.test_pdbfile.TestParsePDBAltloc) ... ok
testAltlocB (prody.tests.proteins.test_pdbfile.TestParsePDBAltloc) ... ok
testAltlocC (prody.tests.proteins.test_pdbfile.TestParsePDBAltloc) ... ok
testAltlocNone (prody.tests.proteins.test_pdbfile.TestParsePDBAltloc) ... ok
testAtomGroupContent (prody.tests.proteins.test_pdbfile.TestParsePDBHeaderAndAllModels) ... ok
testAtomGroupType (prody.tests.proteins.test_pdbfile.TestParsePDBHeaderAndAllModels) ... ok
testResidueCount (prody.tests.sequence.test_analysis.TestCalcMSAOccupancy) ... ok
testResidueOccupancy (prody.tests.sequence.test_analysis.TestCalcMSAOccupancy) ... ok
testSequenceCount (prody.tests.sequence.test_analysis.TestCalcMSAOccupancy) ... ok
testSequenceOccupancy (prody.tests.sequence.test_analysis.TestCalcMSAOccupancy) ... ok
testMATLAB (prody.tests.sequence.test_analysis.TestCalcMeff) ... ok
testTwenty (prody.tests.sequence.test_analysis.TestCalcMeff) ... ok
testTwentyReversed (prody.tests.sequence.test_analysis.TestCalcMeff) ... ok
testZero1 (prody.tests.sequence.test_analysis.TestCalcMeff) ... ok
testZero2 (prody.tests.sequence.test_analysis.TestCalcMeff) ... ok
testAmbiguity (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity2 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity3 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity4 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity5 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity6 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity7 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testInf (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testNoAmbiguity (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testNorm (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testNorm2 (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testSixSequences (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testTwenty (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testTwentyReversed (prody.tests.sequence.test_analysis.TestCalcMutualInfo) ... ok
testAmbiguity (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testAmbiguity2 (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testAmbiguity3 (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testAmbiguity4 (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testAmbiguity5 (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testAmbiguity6 (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testAmbiguity7 (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testFourSequences (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testInf (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testNoAmbiguity (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testTwenty (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testTwentyReversed (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testZero (prody.tests.sequence.test_analysis.TestCalcOMES) ... ok
testMATLAB (prody.tests.sequence.test_analysis.TestCalcSCA) ... /usr/lib64/python2.7/site-packages/numpy/core/fromnumeric.py:2822: RuntimeWarning: overflow encountered in multiply
  return round(decimals, out)
FAIL
testZero (prody.tests.sequence.test_analysis.TestCalcSCA) ... ok
testAmbiguous (prody.tests.sequence.test_analysis.TestCalcShannonEntropy) ... ok
testGapDividend (prody.tests.sequence.test_analysis.TestCalcShannonEntropy) ... ok
testSixSequences (prody.tests.sequence.test_analysis.TestCalcShannonEntropy) ... ok
testSmallProbability (prody.tests.sequence.test_analysis.TestCalcShannonEntropy) ... ok
testTwenty (prody.tests.sequence.test_analysis.TestCalcShannonEntropy) ... ok
testMATLAB10 (prody.tests.sequence.test_analysis.TestDirectInfo) ... FAIL
testMATLAB8 (prody.tests.sequence.test_analysis.TestDirectInfo) ... FAIL
testTwenty (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testTwentyReversed (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testZero (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testZero1 (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testZero2 (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testZero3 (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testZero4 (prody.tests.sequence.test_analysis.TestDirectInfo) ... ok
testIdentityMatrix (prody.tests.sequence.test_analysis.TestIdentity) ... ok
testIdentityMatrixNonTurbo (prody.tests.sequence.test_analysis.TestIdentity) ... ok
testUnique (prody.tests.sequence.test_analysis.TestUnique) ... ok
testUnique2 (prody.tests.sequence.test_analysis.TestUnique) ... ok
testMerge (prody.tests.sequence.test_msa.TestMerging) ... ok
testAll (prody.tests.sequence.test_msa.TestRefinement) ... ok
testColocc (prody.tests.sequence.test_msa.TestRefinement) ... ok
testLabel (prody.tests.sequence.test_msa.TestRefinement) ... ok
testRowCol (prody.tests.sequence.test_msa.TestRefinement) ... ok
testRowocc (prody.tests.sequence.test_msa.TestRefinement) ... ok
testSeqid (prody.tests.sequence.test_msa.TestRefinement) ... ok
testSeqidLabel (prody.tests.sequence.test_msa.TestRefinement) ... ok
testMSAFile (prody.tests.sequence.test_msafile.TestMSAFile) ... ok
testWriteFasta (prody.tests.sequence.test_msafile.TestMSAFile) ... ok
testWriteSelex (prody.tests.sequence.test_msafile.TestMSAFile) ... ok
testWriteStockholm (prody.tests.sequence.test_msafile.TestMSAFile) ... ok
testArray (prody.tests.sequence.test_msafile.TestParseMSA) ... ok
testIterator (prody.tests.sequence.test_msafile.TestParseMSA) ... ok
testMapping (prody.tests.sequence.test_msafile.TestParseMSA) ... ok
testFasta (prody.tests.sequence.test_msafile.TestWriteMSA) ... ok
testSelex (prody.tests.sequence.test_msafile.TestWriteMSA) ... ok
testStringConversion (prody.tests.sequence.test_sequence.TestSequence) ... ok
Failure: IOError (Unrecognized DCD header or unsupported DCD format.) ... ERROR
Failure: IOError (Unrecognized DCD header or unsupported DCD format.) ... ERROR
testCoords (prody.tests.utilities.test_checkers.TestCheckCoords) ... ok
testCoordset (prody.tests.utilities.test_checkers.TestCheckCoords) ... ok
testCoordsetNatoms (prody.tests.utilities.test_checkers.TestCheckCoords) ... ok
testInvalidCoords (prody.tests.utilities.test_checkers.TestCheckCoords) ... ok
testCorrectMonotypeOneArg (prody.tests.utilities.test_checkers.testCheckTypes) ... ok
testCorrectMonotypeTwoArgs (prody.tests.utilities.test_checkers.testCheckTypes) ... ok
testCorrectMultitypeOneArg (prody.tests.utilities.test_checkers.testCheckTypes) ... ok
testWrongMonotypeOneArg (prody.tests.utilities.test_checkers.testCheckTypes) ... ok
testWrongMonotypeTwoArgs (prody.tests.utilities.test_checkers.testCheckTypes) ... ok
testWrongMultitypeOneArg (prody.tests.utilities.test_checkers.testCheckTypes) ... ok
testContinuous (prody.tests.utilities.test_misctools.TestRangeString) ... ok
testGapped (prody.tests.utilities.test_misctools.TestRangeString) ... ok
testNegative (prody.tests.utilities.test_misctools.TestRangeString) ... ok
testRepeated (prody.tests.utilities.test_misctools.TestRangeString) ... ok
testBuffer (prody.tests.utilities.test_pathtools.TestGunzip) ... ok
testFile (prody.tests.utilities.test_pathtools.TestGunzip) ... ok
======================================================================
ERROR: Failure: IOError (Unrecognized DCD header or unsupported DCD format.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/ensemble/__init__.py", line 13, in <module>
    DCD = parseDatafile('dcd')
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/datafiles/__init__.py", line 153, in parseDatafile
    return PARSERS[splitext(fn)[1]](fn, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 494, in parseDCD
    dcd = DCDFile(filename, astype=astype)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: testMSF (prody.tests.measure.test_measure.TestMSF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/measure/test_measure.py", line 106, in testMSF
    dcd = DCDFile(pathDatafile('dcd'))
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: testMSFfloat (prody.tests.measure.test_measure.TestMSF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/measure/test_measure.py", line 113, in testMSFfloat
    dcd = DCDFile(pathDatafile('dcd'), astype=float)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: Failure: IOError (Unrecognized DCD header or unsupported DCD format.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/trajectory/test_dcdfile.py", line 11, in <module>
    from prody.tests.ensemble import ALLATOMS, ENSEMBLE, RTOL, ATOL, DCD
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/ensemble/__init__.py", line 13, in <module>
    DCD = parseDatafile('dcd')
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/datafiles/__init__.py", line 153, in parseDatafile
    return PARSERS[splitext(fn)[1]](fn, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 494, in parseDCD
    dcd = DCDFile(filename, astype=astype)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
ERROR: Failure: IOError (Unrecognized DCD header or unsupported DCD format.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/trajectory/test_frame.py", line 12, in <module>
    DCD = Trajectory(pathDatafile('dcd'))
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/trajectory.py", line 33, in __init__
    self.addFile(name)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/trajectory.py", line 104, in addFile
    traj = openTrajFile(filename, **(kwargs or self._kwargs))
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/__init__.py", line 44, in openTrajFile
    return TRAJFILE[ext](filename, *args, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 52, in __init__
    self._parseHeader()
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/trajectory/dcdfile.py", line 106, in _parseHeader
    raise IOError('Unrecognized DCD header or unsupported '
IOError: Unrecognized DCD header or unsupported DCD format.
======================================================================
FAIL: testMATLAB (prody.tests.sequence.test_analysis.TestCalcSCA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/sequence/test_analysis.py", line 536, in testMATLAB
    assert_array_almost_equal(expect, result, err_msg='turbo failed')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
turbo failed
(mismatch 81.0%)
 x: array([[ -3.425844e+241,   2.556503e-111,  -1.749712e+003,   0.000000e+000,
         -1.681252e-191,  -4.008701e-114,   2.875855e-074,   9.566247e-093,
         -1.292457e-249,  -3.925164e-168],...
 y: array([[ 0.321199,  0.072137,  0.030741,  0.      ,  0.050852,  0.16432 ,
         0.041369,  0.289206,  0.087419,  0.035697],
       [ 0.072137,  0.816631,  0.035063,  0.      ,  0.012006,  0.364268,...
-------------------- >> begin captured logging << --------------------
.prody: DEBUG: SCA matrix was calculated in 0.00s.
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: testMATLAB10 (prody.tests.sequence.test_analysis.TestDirectInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/sequence/test_analysis.py", line 1198, in testMATLAB10
    assert_array_almost_equal(expect, result, err_msg='refine failed')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
refine failed
(mismatch 87.5%)
 x: array([[  0.000000e+000,   1.625806e-028,   3.555451e-017,  -1.228789e+180,
          1.893848e+193,   1.648498e-108,   3.815168e-295,   9.649142e-109],
       [  1.625806e-028,   0.000000e+000,   2.672622e+059,  -1.100353e-256,...
 y: array([[ 0.      ,  1.030514,  1.034746,  0.26286 ,  0.778531,  0.559159,
         0.646177,  0.567633],
       [ 1.030514,  0.      ,  1.161546,  0.148573,  0.728448,  0.528643,...
-------------------- >> begin captured logging << --------------------
.prody: WARNING: WARNING DI performs the best with higher number of sequences, and minimal number of sequences is recommended as 250.
.prody: DEBUG: DI matrix was calculated in 0.00s.
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: testMATLAB8 (prody.tests.sequence.test_analysis.TestDirectInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-5.fc26.ppc64/usr/lib64/python2.7/site-packages/prody/tests/sequence/test_analysis.py", line 1188, in testMATLAB8
    expect, result, err_msg='w/out refine failed')
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
w/out refine failed
(mismatch 87.5%)
 x: array([[  0.000000e+000,   1.625806e-028,   3.555451e-017,  -1.228789e+180,
          1.893848e+193,   1.648498e-108,   3.815168e-295,   9.649142e-109],
       [  1.625806e-028,   0.000000e+000,   2.672622e+059,  -1.100353e-256,...
 y: array([[ 0.      ,  1.030514,  1.034746,  0.26286 ,  0.778531,  0.559159,
         0.646177,  0.567633],
       [ 1.030514,  0.      ,  1.161546,  0.148573,  0.728448,  0.528643,...
-------------------- >> begin captured logging << --------------------
.prody: WARNING: WARNING DI performs the best with higher number of sequences, and minimal number of sequences is recommended as 250.
.prody: DEBUG: DI matrix was calculated in 0.00s.
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 186 tests in 2.661s
FAILED (errors=5, failures=3)
```

Fedora 26 (development branch)
Python 2.7
ProDy 1.8.2
Full log: https://kojipkgs.fedoraproject.org//work/tasks/6398/16976398/build.log

**Comment by sagitter** [comment]
This issue is similar to that of #266.

**Comment by jamesmkrieger** [comment]
Please could you try with the latest ProDy (1.10.7) and tell us if you still have this problem. Thanks

**Comment by jamesmkrieger** [comment]
I am guessing this is not a problem any more and closing it. Feel free to reopen if I am wrong.
