### ISSUE TITLE
TypeError with Python 3.6

### ISSUE THREAD

**Issue by sagitter** [prody/ProDy#363]
Hi all.

This error comes out by testing `ProDy-1.8.2` with `Python3.6` on Fedora 26:

```
======================================================================
ERROR: Failure: TypeError ('float' object cannot be interpreted as an integer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-7.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/tests/ensemble/__init__.py", line 11, in <module>
    ATOMS = parseDatafile('multi_model_truncated', subset='ca')
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-7.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/tests/datafiles/__init__.py", line 153, in parseDatafile
    return PARSERS[splitext(fn)[1]](fn, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-7.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/proteins/pdbfile.py", line 113, in parsePDB
    result = parsePDBStream(pdb, **kwargs)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-7.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/proteins/pdbfile.py", line 186, in parsePDBStream
    _parsePDBLines(ag, lines, split, model, chain, subset, altloc)
  File "/builddir/build/BUILDROOT/ProDy-1.8.2-7.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/proteins/pdbfile.py", line 548, in _parsePDBLines
    coordsets = np.zeros((diff/acount+1, acount, 3))
TypeError: 'float' object cannot be interpreted as an integer
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/566/17700566/build.log

**Comment by SHZ66** [comment]
Hi,

Thank you for reporting the error. I believe that error was fixed in the devel version that is not released yet. A quick workaround is to add an additional slash symbol when dividing diff and account:

1. find and open `pdbfile.py` (the local address is shown in the traceback)
2. goto line 548
3. change the line to `coordsets = np.zeros((diff**//**acount+1, acount, 3))`

**Comment by sagitter** [comment]
Hi @SHZ66.

Your fix works but get an error by `Bytecompiling` during the RPM package building:

```
~/build/BUILD/ProDy-1.8.2/python2 ~/build/BUILD/ProDy-1.8.2
~/build/BUILD/ProDy-1.8.2
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /builddir/build/BUILD/ProDy-1.8.2
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/kdtree/_CKDTree.cpython-36m-x86_64-linux-gnu.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/sequence/seqtools.cpython-36m-x86_64-linux-gnu.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/sequence/msatools.cpython-36m-x86_64-linux-gnu.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/sequence/msaio.cpython-36m-x86_64-linux-gnu.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/dynamics/smtools.cpython-36m-x86_64-linux-gnu.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/dynamics/rtbtools.cpython-36m-x86_64-linux-gnu.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python2.7/site-packages/prody/kdtree/_CKDTree.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python2.7/site-packages/prody/sequence/msatools.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python2.7/site-packages/prody/sequence/seqtools.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python2.7/site-packages/prody/sequence/msaio.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python2.7/site-packages/prody/dynamics/rtbtools.so
extracting debug info from /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python2.7/site-packages/prody/dynamics/smtools.so
/usr/lib/rpm/sepdebugcrcfix: Updated 12 CRC32s, 0 CRC32s did match.
648 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6 using /usr/bin/python3.6
*** Error compiling '/builddir/build/BUILDROOT/ProDy-1.8.2-8.fc26.x86_64/usr/lib64/python3.6/site-packages/prody/proteins/pdbfile.py'...
  File "/usr/lib64/python3.6/pdbfile.py", line 548
    coordsets = np.zeros((diff**//**acount+1, acount, 3))
                                 ^
SyntaxError: invalid syntax
RPM build errors:
```

Full log: https://kojipkgs.fedoraproject.org//work/tasks/6043/17916043/build.log

**Comment by sagitter** [comment]
Thanks for your fix.
