### ISSUE TITLE
Value error: setting an array element with a sequence

### ISSUE THREAD

**Issue by sagitter** [prody/ProDy#455]
Hi all.

`tests/dynamics/test_editing.py` is failing because of error:

```
======================================================================
ERROR: Failure: ValueError (setting an array element with a sequence.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nose/loader.py", line 364, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 84, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/builddir/build/BUILDROOT/ProDy-1.9.3-1.el6.x86_64/usr/lib64/python2.6/site-packages/prody/tests/dynamics/test_editing.py", line 23, in <module>
    GNM = calcGNM(ATOMS)[0]
  File "/builddir/build/BUILDROOT/ProDy-1.9.3-1.el6.x86_64/usr/lib64/python2.6/site-packages/prody/dynamics/gnm.py", line 432, in calcGNM
    gnm.calcModes(n_modes, zeros, hinges=hinges)
  File "/builddir/build/BUILDROOT/ProDy-1.9.3-1.el6.x86_64/usr/lib64/python2.6/site-packages/prody/dynamics/gnm.py", line 306, in calcModes
    self.calcHinges()
  File "/builddir/build/BUILDROOT/ProDy-1.9.3-1.el6.x86_64/usr/lib64/python2.6/site-packages/prody/dynamics/gnm.py", line 332, in calcHinges
    self._hinges = np.array(hinges)
ValueError: setting an array element with a sequence.
----------------------------------------------------------------------
```

Full log: https://koji.fedoraproject.org/koji/getfile?taskID=22916897&volume=DEFAULT&name=build.log
ProDy-1.9.3
Environment: CentOS 6

**Comment by jamesmkrieger** [comment]
All tests pass in the latest version on github and this problem will therefore not exist in the next release. This issue is now closed.
