### ISSUE TITLE
Issue with CryoEM density based Normal mode analysis

### ISSUE THREAD

**Issue by BIORAK** [prody/ProDy#756]
Hi,

   I have been trying to run your cryoEM density based normal mode analysis. I get this error.

Traceback (most recent call last):
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/dynamics/anm.py", line 203, in buildHessian
    coords.getCoords())
AttributeError: 'EMDMAP' object has no attribute 'getCoords'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/utilities/checkers.py", line 34, in checkCoords
    ndim, shape = coords.ndim, coords.shape
AttributeError: 'EMDMAP' object has no attribute 'ndim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/dynamics/anm.py", line 206, in buildHessian
    checkCoords(coords)
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/utilities/checkers.py", line 36, in checkCoords
    raise TypeError('coords must be a numpy.ndarray instance')
TypeError: coords must be a numpy.ndarray instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    anm.buildHessian(emd) 
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/dynamics/anm.py", line 208, in buildHessian
    raise TypeError('coords must be a Numpy array or an object '
TypeError: coords must be a Numpy array or an object with `getCoords` method
[rakesh@pico CryoEMMaps]$ python test.py 
@> Building coordinates from electron density map. This may take a while.
@> 8000 atoms and 1 coordinate sets were parsed in 2555.98s.
Traceback (most recent call last):
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/dynamics/anm.py", line 203, in buildHessian
    coords.getCoords())
AttributeError: 'tuple' object has no attribute 'getCoords'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/utilities/checkers.py", line 34, in checkCoords
    ndim, shape = coords.ndim, coords.shape
AttributeError: 'tuple' object has no attribute 'ndim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/dynamics/anm.py", line 206, in buildHessian
    checkCoords(coords)
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/utilities/checkers.py", line 36, in checkCoords
    raise TypeError('coords must be a numpy.ndarray instance')
TypeError: coords must be a numpy.ndarray instance

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    anm.buildHessian(emd) 
  File "/home/rakesh/WORK/Softwares/Anaconda3/lib/python3.6/site-packages/prody/dynamics/anm.py", line 208, in buildHessian
    raise TypeError('coords must be a Numpy array or an object '
TypeError: coords must be a Numpy array or an object with `getCoords` method

**Comment by SHZ66** [comment]
To build a network model from CryoEM data you need to first obtain coordinates from the electron density map (ENDMAP). There are several algorithms to do that (e.g. Topology representing network), but I need to ask around and maybe look into ProDy to see if we have implemented such functions.

**Comment by BIORAK** [comment]
So this is the code from the tutorial I used ?

from prody import *
import numpy as np
import matplotlib

emd = parseEMD('emd_1960.map', cutoff=1.2, n_nodes=8000, num_iter=30, return_map=True, make_nodes=True)
anm = ANM('TRiC EMDMAP ANM Analysis') 
anm.buildHessian(emd) 
anm.calcModes(n_modes=20) 
writeNMD('tric_anm_3_modes_8000nodes.nmd', anm[:20], emd)

**Comment by jamesmkrieger** [comment]
This should work if you have the file emd_1960.map in your working directory. If you don't then you should probably replace this with '1960' so it will be retrieved from the database first.

Please let me know if that works.

Best wishes
James

**Comment by BIORAK** [comment]
Hi James,

    I ran the code for EM based normal mode. I was able to run it but there are issues with the NMD file (attached here, changed file extension to TXT for github). I don't see pseudoatoms to visualize NM in VMD. Is there a way I can write a PDB file containing the pseudoatoms ?

[tric_anm_3_modes_8000nodes.nmd.txt](https://github.com/prody/ProDy/files/2692680/tric_anm_3_modes_8000nodes.nmd.txt)

Another thing is there a way I can write the deformed models in PDB format based on normal mode.

**Comment by jamesmkrieger** [comment]
It should be possible to see something using NMWiz in VMD. You just need to change the representation from tube to vdw. 

Yes, there is a way to write out deformed structures along modes to pdb files. We have a function called traverseMode that can be used for that. This generates an ensemble that can be written to a PDB file.

**Comment by jamesmkrieger** [comment]
I just opened your nmd file in VMD and using vdw allowed me to see it.

**Comment by jamesmkrieger** [comment]
Please can you confirm whether this solved your problem. Thanks

**Comment by BIORAK** [comment]
Yes the issue was resolved. Thanks James.
